import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import Navbar from './layouts/Navbar/Navbar'
import Footer from './layouts/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="nando">
      
        <Head>
          <title>NandoShop</title>
        </Head>

      <body className={inter.className}>
      {/* <main className="flex min-h-screen flex-col items-center justify-between p-24"> */}
        <Navbar />
        <main className="pt-28">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
